export const cardValue = [
  {
    time: '00:00',
    srcIcon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
    temperature: '+6',
    feelsLike: '+7',
    chanceOfRain: '0',
    chanceOfSnow: '0',
    precipi: '0',
    pressure: '1023',
    wind: '9,4',
    humidity: '84',
    uvIndex: '1',
    gust: '14,3',
    vis: '10',
    heatIndex: '5,3',
    cloud: '52',
    windchill: '2.1',
  },
  {
    time: '02:00',
    srcIcon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
    temperature: '+3',
    feelsLike: '+1',
    chanceOfRain: '1',
    chanceOfSnow: '1',
    precipi: '0',
    pressure: '843',
    wind: '4,4',
    humidity: '100',
    uvIndex: '2',
    gust: '11,3',
    vis: '3',
    heatIndex: '2,3',
    cloud: '72',
    windchill: '3.1',
  },
  {
    time: '04:00',
    srcIcon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
    temperature: '-23',
    feelsLike: '+0',
    chanceOfRain: '0',
    chanceOfSnow: '0',
    precipi: '0',
    pressure: '530',
    wind: '5,4',
    humidity: '76',
    uvIndex: '1',
    gust: '9,3',
    vis: '9',
    heatIndex: '4,3',
    cloud: '30',
    windchill: '3.1',
  },
  {
    time: '06:00',
    srcIcon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
    temperature: '+7',
    feelsLike: '+3',
    chanceOfRain: '1',
    chanceOfSnow: '0',
    precipi: '4',
    pressure: '1102',
    wind: '13,4',
    humidity: '99',
    uvIndex: '1',
    gust: '2,3',
    vis: '7',
    heatIndex: '6,3',
    cloud: '42',
    windchill: '6.1',
  },
  {
    time: '08:00',
    srcIcon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
    temperature: '+9',
    feelsLike: '+3',
    chanceOfRain: '0',
    chanceOfSnow: '1',
    precipi: '5',
    pressure: '823',
    wind: '3,3',
    humidity: '58',
    uvIndex: '0',
    gust: '13,6',
    vis: '7',
    heatIndex: '3,3',
    cloud: '47',
    windchill: '3.9',
  },
  {
    time: '10:00',
    srcIcon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
    temperature: '+2',
    feelsLike: '0',
    chanceOfRain: '0',
    chanceOfSnow: '1',
    precipi: '1',
    pressure: '1223',
    wind: '8,9',
    humidity: '65',
    uvIndex: '0',
    gust: '12,5',
    vis: '6',
    heatIndex: '3,0',
    cloud: '86',
    windchill: '7.4',
  },
  {
    time: '12:00',
    srcIcon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
    temperature: '+12',
    feelsLike: '+3',
    chanceOfRain: '0',
    chanceOfSnow: '0',
    precipi: '0',
    pressure: '1023',
    wind: '9,4',
    humidity: '84',
    uvIndex: '1',
    gust: '14,3',
    vis: '10',
    heatIndex: '5,3',
    cloud: '52',
    windchill: '2.1',
  },
  {
    time: '14:00',
    srcIcon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
    temperature: '+6',
    feelsLike: '+7',
    chanceOfRain: '1',
    chanceOfSnow: '0',
    precipi: '0',
    pressure: '623',
    wind: '7,7',
    humidity: '12',
    uvIndex: '1',
    gust: '16,0',
    vis: '7',
    heatIndex: '3,8',
    cloud: '45',
    windchill: '1.6',
  },
  {
    time: '16:00',
    srcIcon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
    temperature: '+6',
    feelsLike: '+7',
    chanceOfRain: '0',
    chanceOfSnow: '0',
    precipi: '0',
    pressure: '1023',
    wind: '9,4',
    humidity: '84',
    uvIndex: '1',
    gust: '14,3',
    vis: '10',
    heatIndex: '5,3',
    cloud: '52',
    windchill: '2.1',
  },
  {
    time: '18:00',
    srcIcon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
    temperature: '+6',
    feelsLike: '+7',
    chanceOfRain: '1',
    chanceOfSnow: '0',
    precipi: '0',
    pressure: '823',
    wind: '9,4',
    humidity: '84',
    uvIndex: '0',
    gust: '13,6',
    vis: '5',
    heatIndex: '7,3',
    cloud: '56',
    windchill: '7.1',
  },
  {
    time: '20:00',
    srcIcon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
    temperature: '+8',
    feelsLike: '+1',
    chanceOfRain: '1',
    chanceOfSnow: '0',
    precipi: '1',
    pressure: '623',
    wind: '3,4',
    humidity: '45',
    uvIndex: '0',
    gust: '11,3',
    vis: '7',
    heatIndex: '3,3',
    cloud: '67',
    windchill: '3.8',
  },
  {
    time: '22:00',
    srcIcon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
    temperature: '+5',
    feelsLike: '+1',
    chanceOfRain: '0',
    chanceOfSnow: '0',
    precipi: '0',
    pressure: '1145',
    wind: '3,5',
    humidity: '43',
    uvIndex: '1',
    gust: '34,5',
    vis: '10',
    heatIndex: '4,3',
    cloud: '45',
    windchill: '2.1',
  },
  {
    time: '24:00',
    srcIcon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
    temperature: '+6',
    feelsLike: '+7',
    chanceOfRain: '0',
    chanceOfSnow: '0',
    precipi: '0',
    pressure: '1023',
    wind: '9,4',
    humidity: '84',
    uvIndex: '1',
    gust: '14,3',
    vis: '10',
    heatIndex: '5,3',
    cloud: '52',
    windchill: '2.1',
  },
]
